(vector-length '#())
(vector-length (vector))
(define emptier '#())
(vector-length emptier)
(vector-length '#(1))
(vector-length '#(1 #\1))
(vector-length '#("maor" #\x53))
(vector-length '#("\t" "\f"))
(vector-length '#("\x53;" "\\"))
(define vectorer '#(1 2 3 4 #t #f))
(vector-length vectorer)
(define checker (lambda (x) (vector-length x)))
(checker vectorer)
(checker emptier)
(eq? (checker vectorer) 6)
(eq? (checker vectorer) 18/3)
(eq? (checker vectorer) 7)
(eq? (checker emptier) 0)
(define vectorer2 '#(4 5 6 7 #f #t))
(eq? (vector-length vectorer) (vector-length vectorer2))